package hospital.management.backend.model.finance;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity model for the `invoices` table.
 * Every column in the schema is represented as a field below.
 */
public class Invoice {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String invoiceId;
    /** FK -> appointments */
    private String appointmentId;
    /** FK -> patients */
    private String patientId;
    private BigDecimal totalAmount;
    /** 'unpaid', 'partially_paid', or 'paid' */
    private String paymentStatus;
    /** acts as this table's created_at */
    private LocalDateTime issuedAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public Invoice() {
    }

    public Invoice(String invoiceId, String appointmentId, String patientId, BigDecimal totalAmount, String paymentStatus, LocalDateTime issuedAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.invoiceId = invoiceId;
        this.appointmentId = appointmentId;
        this.patientId = patientId;
        this.totalAmount = totalAmount;
        this.paymentStatus = paymentStatus;
        this.issuedAt = issuedAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getInvoiceId() {
        return invoiceId;
    }

    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId;
    }

    public String getAppointmentId() {
        return appointmentId;
    }

    public void setAppointmentId(String appointmentId) {
        this.appointmentId = appointmentId;
    }

    public String getPatientId() {
        return patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public String getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    public LocalDateTime getIssuedAt() {
        return issuedAt;
    }

    public void setIssuedAt(LocalDateTime issuedAt) {
        this.issuedAt = issuedAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "Invoice{" + "invoiceId=" + invoiceId + ", " + "appointmentId=" + appointmentId + ", " + "patientId=" + patientId + ", " + "totalAmount=" + totalAmount + ", " + "paymentStatus=" + paymentStatus + ", " + "issuedAt=" + issuedAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}