package hospital.management.backend.model.doctor;

import java.time.LocalDateTime;

/**
 * Entity model for the `departments` table.
 * Placed in the doctor package because Doctor is the only entity that holds
 * a FK to this table (department_id).
 */
public class Department {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String departmentId;
    /** NOT NULL, UNIQUE */
    private String name;
    private String location;
    private String phone;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    /** soft delete marker, null = active */
    private LocalDateTime deletedAt;

    public Department() {
    }

    public Department(String departmentId, String name, String location, String phone, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.departmentId = departmentId;
        this.name = name;
        this.location = location;
        this.phone = phone;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "Department{" + "departmentId=" + departmentId + ", " + "name=" + name + ", " + "location=" + location + ", " + "phone=" + phone + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}