package hospital.management.backend.model.doctor;

import java.time.LocalDateTime;
import java.time.LocalTime;

/**
 * Entity model for the `doctor_schedules` table.
 * Every column in the schema is represented as a field below.
 */
public class DoctorSchedule {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String scheduleId;
    /** FK -> doctors */
    private String doctorId;
    /** 'Mon'..'Sun' */
    private String dayOfWeek;
    private LocalTime startTime;
    /** must be after startTime */
    private LocalTime endTime;
    private Boolean isAvailable;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public DoctorSchedule() {
    }

    public DoctorSchedule(String scheduleId, String doctorId, String dayOfWeek, LocalTime startTime, LocalTime endTime, Boolean isAvailable, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.scheduleId = scheduleId;
        this.doctorId = doctorId;
        this.dayOfWeek = dayOfWeek;
        this.startTime = startTime;
        this.endTime = endTime;
        this.isAvailable = isAvailable;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getScheduleId() {
        return scheduleId;
    }

    public void setScheduleId(String scheduleId) {
        this.scheduleId = scheduleId;
    }

    public String getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    public String getDayOfWeek() {
        return dayOfWeek;
    }

    public void setDayOfWeek(String dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    public LocalTime getStartTime() {
        return startTime;
    }

    public void setStartTime(LocalTime startTime) {
        this.startTime = startTime;
    }

    public LocalTime getEndTime() {
        return endTime;
    }

    public void setEndTime(LocalTime endTime) {
        this.endTime = endTime;
    }

    public Boolean isIsAvailable() {
        return isAvailable;
    }

    public void setIsAvailable(Boolean isAvailable) {
        this.isAvailable = isAvailable;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "DoctorSchedule{" + "scheduleId=" + scheduleId + ", " + "doctorId=" + doctorId + ", " + "dayOfWeek=" + dayOfWeek + ", " + "startTime=" + startTime + ", " + "endTime=" + endTime + ", " + "isAvailable=" + isAvailable + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}