package hospital.management.backend.model.doctor;

import java.time.LocalDateTime;

/**
 * Entity model for the `doctors` table.
 * Every column in the schema is represented as a field below.
 */
public class Doctor {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String doctorId;
    /** FK -> departments */
    private String departmentId;
    /** NOT NULL */
    private String firstName;
    /** NOT NULL */
    private String lastName;
    private String specialization;
    private String phone;
    /** UNIQUE */
    private String email;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public Doctor() {
    }

    public Doctor(String doctorId, String departmentId, String firstName, String lastName, String specialization, String phone, String email, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.doctorId = doctorId;
        this.departmentId = departmentId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.specialization = specialization;
        this.phone = phone;
        this.email = email;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    public String getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getSpecialization() {
        return specialization;
    }

    public void setSpecialization(String specialization) {
        this.specialization = specialization;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "Doctor{" + "doctorId=" + doctorId + ", " + "departmentId=" + departmentId + ", " + "firstName=" + firstName + ", " + "lastName=" + lastName + ", " + "specialization=" + specialization + ", " + "phone=" + phone + ", " + "email=" + email + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}