package hospital.management.backend.model.doctor;

import java.time.LocalDateTime;

/**
 * Entity model for the `referrals` table.
 * Placed in the doctor package because a referral is a doctor-to-doctor
 * linkage (referring_doctor_id → referred_to_doctor_id), both FKing doctors.
 */
public class Referral {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String referralId;
    /** FK -> appointments */
    private String appointmentId;
    /** FK -> doctors */
    private String referringDoctorId;
    /** FK -> doctors, must differ from referringDoctorId */
    private String referredToDoctorId;
    private String reason;
    /** 'pending', 'scheduled', or 'completed' */
    private String status;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public Referral() {
    }

    public Referral(String referralId, String appointmentId, String referringDoctorId, String referredToDoctorId, String reason, String status, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.referralId = referralId;
        this.appointmentId = appointmentId;
        this.referringDoctorId = referringDoctorId;
        this.referredToDoctorId = referredToDoctorId;
        this.reason = reason;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getReferralId() {
        return referralId;
    }

    public void setReferralId(String referralId) {
        this.referralId = referralId;
    }

    public String getAppointmentId() {
        return appointmentId;
    }

    public void setAppointmentId(String appointmentId) {
        this.appointmentId = appointmentId;
    }

    public String getReferringDoctorId() {
        return referringDoctorId;
    }

    public void setReferringDoctorId(String referringDoctorId) {
        this.referringDoctorId = referringDoctorId;
    }

    public String getReferredToDoctorId() {
        return referredToDoctorId;
    }

    public void setReferredToDoctorId(String referredToDoctorId) {
        this.referredToDoctorId = referredToDoctorId;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "Referral{" + "referralId=" + referralId + ", " + "appointmentId=" + appointmentId + ", " + "referringDoctorId=" + referringDoctorId + ", " + "referredToDoctorId=" + referredToDoctorId + ", " + "reason=" + reason + ", " + "status=" + status + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}