package hospital.management.backend.model.lab;

import java.time.LocalDateTime;

/**
 * Entity model for the `lab_orders` table.
 * Every column in the schema is represented as a field below.
 */
public class LabOrder {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String labOrderId;
    /** FK -> appointments */
    private String appointmentId;
    /** FK -> doctors */
    private String doctorId;
    /** NOT NULL */
    private String testName;
    /** 'ordered', 'in_progress', 'completed', or 'cancelled' */
    private String status;
    /** acts as this table's created_at */
    private LocalDateTime orderedAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public LabOrder() {
    }

    public LabOrder(String labOrderId, String appointmentId, String doctorId, String testName, String status, LocalDateTime orderedAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.labOrderId = labOrderId;
        this.appointmentId = appointmentId;
        this.doctorId = doctorId;
        this.testName = testName;
        this.status = status;
        this.orderedAt = orderedAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getLabOrderId() {
        return labOrderId;
    }

    public void setLabOrderId(String labOrderId) {
        this.labOrderId = labOrderId;
    }

    public String getAppointmentId() {
        return appointmentId;
    }

    public void setAppointmentId(String appointmentId) {
        this.appointmentId = appointmentId;
    }

    public String getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    public String getTestName() {
        return testName;
    }

    public void setTestName(String testName) {
        this.testName = testName;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getOrderedAt() {
        return orderedAt;
    }

    public void setOrderedAt(LocalDateTime orderedAt) {
        this.orderedAt = orderedAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "LabOrder{" + "labOrderId=" + labOrderId + ", " + "appointmentId=" + appointmentId + ", " + "doctorId=" + doctorId + ", " + "testName=" + testName + ", " + "status=" + status + ", " + "orderedAt=" + orderedAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}