package hospital.management.backend.model.lab;

import java.time.LocalDateTime;

/**
 * Entity model for the `lab_results` table.
 * Every column in the schema is represented as a field below.
 */
public class LabResult {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String labResultId;
    /** FK -> lab_orders, UNIQUE (1:1) */
    private String labOrderId;
    private String resultValue;
    private String unit;
    private String referenceRange;
    private Boolean isAbnormal;
    private LocalDateTime completedAt;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public LabResult() {
    }

    public LabResult(String labResultId, String labOrderId, String resultValue, String unit, String referenceRange, Boolean isAbnormal, LocalDateTime completedAt, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.labResultId = labResultId;
        this.labOrderId = labOrderId;
        this.resultValue = resultValue;
        this.unit = unit;
        this.referenceRange = referenceRange;
        this.isAbnormal = isAbnormal;
        this.completedAt = completedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getLabResultId() {
        return labResultId;
    }

    public void setLabResultId(String labResultId) {
        this.labResultId = labResultId;
    }

    public String getLabOrderId() {
        return labOrderId;
    }

    public void setLabOrderId(String labOrderId) {
        this.labOrderId = labOrderId;
    }

    public String getResultValue() {
        return resultValue;
    }

    public void setResultValue(String resultValue) {
        this.resultValue = resultValue;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getReferenceRange() {
        return referenceRange;
    }

    public void setReferenceRange(String referenceRange) {
        this.referenceRange = referenceRange;
    }

    public Boolean isIsAbnormal() {
        return isAbnormal;
    }

    public void setIsAbnormal(Boolean isAbnormal) {
        this.isAbnormal = isAbnormal;
    }

    public LocalDateTime getCompletedAt() {
        return completedAt;
    }

    public void setCompletedAt(LocalDateTime completedAt) {
        this.completedAt = completedAt;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "LabResult{" + "labResultId=" + labResultId + ", " + "labOrderId=" + labOrderId + ", " + "resultValue=" + resultValue + ", " + "unit=" + unit + ", " + "referenceRange=" + referenceRange + ", " + "isAbnormal=" + isAbnormal + ", " + "completedAt=" + completedAt + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}