package hospital.management.backend.model.pharmacy;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Entity model for the `medical_inventory` table.
 * Placed in the pharmacy package because it tracks stock batches for
 * Medication and is consumed by sp_issue_prescription.
 */
public class MedicalInventory {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String inventoryId;
    /** FK -> medications */
    private String medicationId;
    private String batchNumber;
    /** NOT NULL */
    private LocalDate expiryDate;
    private Integer quantityInStock;
    private Integer reorderLevel;
    private String supplier;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public MedicalInventory() {
    }

    public MedicalInventory(String inventoryId, String medicationId, String batchNumber, LocalDate expiryDate, Integer quantityInStock, Integer reorderLevel, String supplier, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.inventoryId = inventoryId;
        this.medicationId = medicationId;
        this.batchNumber = batchNumber;
        this.expiryDate = expiryDate;
        this.quantityInStock = quantityInStock;
        this.reorderLevel = reorderLevel;
        this.supplier = supplier;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getInventoryId() {
        return inventoryId;
    }

    public void setInventoryId(String inventoryId) {
        this.inventoryId = inventoryId;
    }

    public String getMedicationId() {
        return medicationId;
    }

    public void setMedicationId(String medicationId) {
        this.medicationId = medicationId;
    }

    public String getBatchNumber() {
        return batchNumber;
    }

    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber;
    }

    public LocalDate getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(LocalDate expiryDate) {
        this.expiryDate = expiryDate;
    }

    public Integer getQuantityInStock() {
        return quantityInStock;
    }

    public void setQuantityInStock(Integer quantityInStock) {
        this.quantityInStock = quantityInStock;
    }

    public Integer getReorderLevel() {
        return reorderLevel;
    }

    public void setReorderLevel(Integer reorderLevel) {
        this.reorderLevel = reorderLevel;
    }

    public String getSupplier() {
        return supplier;
    }

    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "MedicalInventory{" + "inventoryId=" + inventoryId + ", " + "medicationId=" + medicationId + ", " + "batchNumber=" + batchNumber + ", " + "expiryDate=" + expiryDate + ", " + "quantityInStock=" + quantityInStock + ", " + "reorderLevel=" + reorderLevel + ", " + "supplier=" + supplier + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}