package hospital.management.backend.model.pharmacy;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity model for the `medications` table.
 * Anchor of the pharmacy package: MedicalInventory and PrescriptionItem
 * both hold a FK to this table.
 */
public class Medication {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String medicationId;
    /** NOT NULL */
    private String name;
    private String genericName;
    /** e.g. tablet, syrup */
    private String form;
    private BigDecimal unitPrice;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public Medication() {
    }

    public Medication(String medicationId, String name, String genericName, String form, BigDecimal unitPrice, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.medicationId = medicationId;
        this.name = name;
        this.genericName = genericName;
        this.form = form;
        this.unitPrice = unitPrice;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getMedicationId() {
        return medicationId;
    }

    public void setMedicationId(String medicationId) {
        this.medicationId = medicationId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getGenericName() {
        return genericName;
    }

    public void setGenericName(String genericName) {
        this.genericName = genericName;
    }

    public String getForm() {
        return form;
    }

    public void setForm(String form) {
        this.form = form;
    }

    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "Medication{" + "medicationId=" + medicationId + ", " + "name=" + name + ", " + "genericName=" + genericName + ", " + "form=" + form + ", " + "unitPrice=" + unitPrice + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}