package hospital.management.backend.model.pharmacy;

import java.time.LocalDateTime;

/**
 * Entity model for the `prescription_items` table.
 * Placed in the pharmacy package: each line item links a Prescription
 * to a Medication and drives stock deduction in sp_issue_prescription.
 */
public class PrescriptionItem {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String itemId;
    /** FK -> prescriptions */
    private String prescriptionId;
    /** FK -> medications */
    private String medicationId;
    private String dosage;
    private Integer quantity;
    private String instructions;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public PrescriptionItem() {
    }

    public PrescriptionItem(String itemId, String prescriptionId, String medicationId, String dosage, Integer quantity, String instructions, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.itemId = itemId;
        this.prescriptionId = prescriptionId;
        this.medicationId = medicationId;
        this.dosage = dosage;
        this.quantity = quantity;
        this.instructions = instructions;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getItemId() {
        return itemId;
    }

    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    public String getPrescriptionId() {
        return prescriptionId;
    }

    public void setPrescriptionId(String prescriptionId) {
        this.prescriptionId = prescriptionId;
    }

    public String getMedicationId() {
        return medicationId;
    }

    public void setMedicationId(String medicationId) {
        this.medicationId = medicationId;
    }

    public String getDosage() {
        return dosage;
    }

    public void setDosage(String dosage) {
        this.dosage = dosage;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public String getInstructions() {
        return instructions;
    }

    public void setInstructions(String instructions) {
        this.instructions = instructions;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "PrescriptionItem{" + "itemId=" + itemId + ", " + "prescriptionId=" + prescriptionId + ", " + "medicationId=" + medicationId + ", " + "dosage=" + dosage + ", " + "quantity=" + quantity + ", " + "instructions=" + instructions + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}