package hospital.management.backend.model.pharmacy;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Entity model for the `prescriptions` table.
 * Placed in the pharmacy package: a prescription is the header record
 * for a set of PrescriptionItems, each of which references a Medication.
 */
public class Prescription {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String prescriptionId;
    /** FK -> appointments */
    private String appointmentId;
    private LocalDate dateIssued;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public Prescription() {
    }

    public Prescription(String prescriptionId, String appointmentId, LocalDate dateIssued, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.prescriptionId = prescriptionId;
        this.appointmentId = appointmentId;
        this.dateIssued = dateIssued;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getPrescriptionId() {
        return prescriptionId;
    }

    public void setPrescriptionId(String prescriptionId) {
        this.prescriptionId = prescriptionId;
    }

    public String getAppointmentId() {
        return appointmentId;
    }

    public void setAppointmentId(String appointmentId) {
        this.appointmentId = appointmentId;
    }

    public LocalDate getDateIssued() {
        return dateIssued;
    }

    public void setDateIssued(LocalDate dateIssued) {
        this.dateIssued = dateIssued;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "Prescription{" + "prescriptionId=" + prescriptionId + ", " + "appointmentId=" + appointmentId + ", " + "dateIssued=" + dateIssued + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}