package hospital.management.backend.model.user;

import java.time.LocalDateTime;

/**
 * Entity model for the `audit_log` table.
 * Placed in the user package because every audit entry is optionally
 * linked to a User via the user_id FK.
 */
public class AuditLog {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String logId;
    /** FK -> users, nullable */
    private String userId;
    /** NOT NULL */
    private String action;
    /** NOT NULL */
    private String tableAffected;
    /** UUID of the affected row in tableAffected, nullable */
    private String recordId;
    /** append-only: no updatedAt/deletedAt on this table */
    private LocalDateTime createdAt;

    public AuditLog() {
    }

    public AuditLog(String logId, String userId, String action, String tableAffected, String recordId, LocalDateTime createdAt) {
        this.logId = logId;
        this.userId = userId;
        this.action = action;
        this.tableAffected = tableAffected;
        this.recordId = recordId;
        this.createdAt = createdAt;
    }

    public String getLogId() {
        return logId;
    }

    public void setLogId(String logId) {
        this.logId = logId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getTableAffected() {
        return tableAffected;
    }

    public void setTableAffected(String tableAffected) {
        this.tableAffected = tableAffected;
    }

    public String getRecordId() {
        return recordId;
    }

    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "AuditLog{" + "logId=" + logId + ", " + "userId=" + userId + ", " + "action=" + action + ", " + "tableAffected=" + tableAffected + ", " + "recordId=" + recordId + ", " + "createdAt=" + createdAt + "}";
    }
}