package hospital.management.backend.model.user;

import java.time.LocalDateTime;

/**
 * Entity model for the `permissions` table.
 * Every column in the schema is represented as a field below.
 */
public class Permission {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String permissionId;
    /** NOT NULL */
    private String resource;
    /** NOT NULL */
    private String action;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public Permission() {
    }

    public Permission(String permissionId, String resource, String action, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.permissionId = permissionId;
        this.resource = resource;
        this.action = action;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getPermissionId() {
        return permissionId;
    }

    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId;
    }

    public String getResource() {
        return resource;
    }

    public void setResource(String resource) {
        this.resource = resource;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "Permission{" + "permissionId=" + permissionId + ", " + "resource=" + resource + ", " + "action=" + action + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}