package hospital.management.backend.model.user;

import java.time.LocalDateTime;

/**
 * Entity model for the `system_logs` table.
 * Placed in the user package because every system log entry is optionally
 * linked to a User via the user_id FK.
 */
public class SystemLog {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String logId;
    /** 'DEBUG', 'INFO', 'WARNING', or 'ERROR' */
    private String logLevel;
    /** module/class name */
    private String source;
    /** NOT NULL */
    private String message;
    /** FK -> users, nullable */
    private String userId;
    /** append-only: no updatedAt/deletedAt on this table */
    private LocalDateTime createdAt;

    public SystemLog() {
    }

    public SystemLog(String logId, String logLevel, String source, String message, String userId, LocalDateTime createdAt) {
        this.logId = logId;
        this.logLevel = logLevel;
        this.source = source;
        this.message = message;
        this.userId = userId;
        this.createdAt = createdAt;
    }

    public String getLogId() {
        return logId;
    }

    public void setLogId(String logId) {
        this.logId = logId;
    }

    public String getLogLevel() {
        return logLevel;
    }

    public void setLogLevel(String logLevel) {
        this.logLevel = logLevel;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "SystemLog{" + "logId=" + logId + ", " + "logLevel=" + logLevel + ", " + "source=" + source + ", " + "message=" + message + ", " + "userId=" + userId + ", " + "createdAt=" + createdAt + "}";
    }
}