package hospital.management.backend.model.user;

import java.time.LocalDateTime;

/**
 * Entity model for the `user_sessions` table.
 * Every column in the schema is represented as a field below.
 */
public class UserSession {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String sessionId;
    /** FK -> users, NOT NULL */
    private String userId;
    /** acts as this table's created_at */
    private LocalDateTime loginAt;
    private LocalDateTime logoutAt;
    /** NOT NULL */
    private LocalDateTime expiresAt;
    private String ipAddress;
    private String userAgent;
    private Boolean isActive;
    private LocalDateTime updatedAt;

    public UserSession() {
    }

    public UserSession(String sessionId, String userId, LocalDateTime loginAt, LocalDateTime logoutAt, LocalDateTime expiresAt, String ipAddress, String userAgent, Boolean isActive, LocalDateTime updatedAt) {
        this.sessionId = sessionId;
        this.userId = userId;
        this.loginAt = loginAt;
        this.logoutAt = logoutAt;
        this.expiresAt = expiresAt;
        this.ipAddress = ipAddress;
        this.userAgent = userAgent;
        this.isActive = isActive;
        this.updatedAt = updatedAt;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public LocalDateTime getLoginAt() {
        return loginAt;
    }

    public void setLoginAt(LocalDateTime loginAt) {
        this.loginAt = loginAt;
    }

    public LocalDateTime getLogoutAt() {
        return logoutAt;
    }

    public void setLogoutAt(LocalDateTime logoutAt) {
        this.logoutAt = logoutAt;
    }

    public LocalDateTime getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public String getUserAgent() {
        return userAgent;
    }

    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    public Boolean isIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        return "UserSession{" + "sessionId=" + sessionId + ", " + "userId=" + userId + ", " + "loginAt=" + loginAt + ", " + "logoutAt=" + logoutAt + ", " + "expiresAt=" + expiresAt + ", " + "ipAddress=" + ipAddress + ", " + "userAgent=" + userAgent + ", " + "isActive=" + isActive + ", " + "updatedAt=" + updatedAt + "}";
    }
}