package hospital.management.backend.model.patient;

import java.time.LocalDateTime;

/**
 * Entity model for the `appointments` table.
 * Every column in the schema is represented as a field below.
 */
public class Appointment {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String appointmentId;
    /** FK -> patients, NOT NULL */
    private String patientId;
    /** FK -> doctors, NOT NULL */
    private String doctorId;
    /** NOT NULL */
    private LocalDateTime appointmentDate;
    /** 'scheduled', 'completed', or 'cancelled' */
    private String status;
    private String reason;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public Appointment() {
    }

    public Appointment(String appointmentId, String patientId, String doctorId, LocalDateTime appointmentDate, String status, String reason, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.appointmentId = appointmentId;
        this.patientId = patientId;
        this.doctorId = doctorId;
        this.appointmentDate = appointmentDate;
        this.status = status;
        this.reason = reason;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getAppointmentId() {
        return appointmentId;
    }

    public void setAppointmentId(String appointmentId) {
        this.appointmentId = appointmentId;
    }

    public String getPatientId() {
        return patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    public LocalDateTime getAppointmentDate() {
        return appointmentDate;
    }

    public void setAppointmentDate(LocalDateTime appointmentDate) {
        this.appointmentDate = appointmentDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "Appointment{" + "appointmentId=" + appointmentId + ", " + "patientId=" + patientId + ", " + "doctorId=" + doctorId + ", " + "appointmentDate=" + appointmentDate + ", " + "status=" + status + ", " + "reason=" + reason + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}