package hospital.management.backend.model.patient;

import java.time.LocalDateTime;

/**
 * Entity model for the `medical_records` table.
 * Placed in the patient package because a medical record is 1:0..1 with
 * Appointment, which is itself a core patient-care entity.
 */
public class MedicalRecord {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String recordId;
    /** FK -> appointments, UNIQUE (1:0..1) */
    private String appointmentId;
    private String diagnosis;
    private String symptoms;
    private String notes;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public MedicalRecord() {
    }

    public MedicalRecord(String recordId, String appointmentId, String diagnosis, String symptoms, String notes, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.recordId = recordId;
        this.appointmentId = appointmentId;
        this.diagnosis = diagnosis;
        this.symptoms = symptoms;
        this.notes = notes;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getRecordId() {
        return recordId;
    }

    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    public String getAppointmentId() {
        return appointmentId;
    }

    public void setAppointmentId(String appointmentId) {
        this.appointmentId = appointmentId;
    }

    public String getDiagnosis() {
        return diagnosis;
    }

    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis;
    }

    public String getSymptoms() {
        return symptoms;
    }

    public void setSymptoms(String symptoms) {
        this.symptoms = symptoms;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "MedicalRecord{" + "recordId=" + recordId + ", " + "appointmentId=" + appointmentId + ", " + "diagnosis=" + diagnosis + ", " + "symptoms=" + symptoms + ", " + "notes=" + notes + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}