package hospital.management.backend.model.patient;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Entity model for the `patient_feedback` table.
 * Every column in the schema is represented as a field below.
 */
public class PatientFeedback {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String feedbackId;
    /** FK -> users - who submitted the feedback */
    private String submittedBy;
    /** FK -> patients - patient the feedback is about (nullable) */
    private String patientId;
    /** FK -> appointments, nullable */
    private String appointmentId;
    /** 1-5 */
    private Integer rating;
    private String comments;
    private LocalDate dateSubmitted;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public PatientFeedback() {
    }

    public PatientFeedback(String feedbackId, String submittedBy, String patientId, String appointmentId, Integer rating, String comments, LocalDate dateSubmitted, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.feedbackId = feedbackId;
        this.submittedBy = submittedBy;
        this.patientId = patientId;
        this.appointmentId = appointmentId;
        this.rating = rating;
        this.comments = comments;
        this.dateSubmitted = dateSubmitted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getFeedbackId() {
        return feedbackId;
    }

    public void setFeedbackId(String feedbackId) {
        this.feedbackId = feedbackId;
    }

    public String getSubmittedBy() {
        return submittedBy;
    }

    public void setSubmittedBy(String submittedBy) {
        this.submittedBy = submittedBy;
    }

    public String getPatientId() {
        return patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getAppointmentId() {
        return appointmentId;
    }

    public void setAppointmentId(String appointmentId) {
        this.appointmentId = appointmentId;
    }

    public Integer getRating() {
        return rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public LocalDate getDateSubmitted() {
        return dateSubmitted;
    }

    public void setDateSubmitted(LocalDate dateSubmitted) {
        this.dateSubmitted = dateSubmitted;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "PatientFeedback{" + "feedbackId=" + feedbackId + ", " + "patientId=" + patientId + ", " + "appointmentId=" + appointmentId + ", " + "rating=" + rating + ", " + "comments=" + comments + ", " + "dateSubmitted=" + dateSubmitted + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}