package hospital.management.backend.model.patient;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Entity model for the `patients` table.
 * Every column in the schema is represented as a field below.
 */
public class Patient {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String patientId;
    /** NOT NULL */
    private String firstName;
    /** NOT NULL */
    private String lastName;
    /** NOT NULL */
    private LocalDate dob;
    /** 'M', 'F', or 'Other' */
    private String gender;
    private String phone;
    private String email;
    private String address;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public Patient() {
    }

    public Patient(String patientId, String firstName, String lastName, LocalDate dob, String gender, String phone, String email, String address, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.patientId = patientId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dob = dob;
        this.gender = gender;
        this.phone = phone;
        this.email = email;
        this.address = address;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getPatientId() {
        return patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public LocalDate getDob() {
        return dob;
    }

    public void setDob(LocalDate dob) {
        this.dob = dob;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "Patient{" + "patientId=" + patientId + ", " + "firstName=" + firstName + ", " + "lastName=" + lastName + ", " + "dob=" + dob + ", " + "gender=" + gender + ", " + "phone=" + phone + ", " + "email=" + email + ", " + "address=" + address + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}