package hospital.management.backend.model.patient;

import java.time.LocalDateTime;

/**
 * Entity model for the `patient_allergies` table.
 * Every column in the schema is represented as a field below.
 */
public class PatientAllergy {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String allergyId;
    /** FK -> patients */
    private String patientId;
    /** NOT NULL */
    private String allergen;
    private String reaction;
    /** 'mild', 'moderate', or 'severe' */
    private String severity;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public PatientAllergy() {
    }

    public PatientAllergy(String allergyId, String patientId, String allergen, String reaction, String severity, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.allergyId = allergyId;
        this.patientId = patientId;
        this.allergen = allergen;
        this.reaction = reaction;
        this.severity = severity;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getAllergyId() {
        return allergyId;
    }

    public void setAllergyId(String allergyId) {
        this.allergyId = allergyId;
    }

    public String getPatientId() {
        return patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getAllergen() {
        return allergen;
    }

    public void setAllergen(String allergen) {
        this.allergen = allergen;
    }

    public String getReaction() {
        return reaction;
    }

    public void setReaction(String reaction) {
        this.reaction = reaction;
    }

    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "PatientAllergy{" + "allergyId=" + allergyId + ", " + "patientId=" + patientId + ", " + "allergen=" + allergen + ", " + "reaction=" + reaction + ", " + "severity=" + severity + ", " + "createdAt=" + createdAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}