package hospital.management.backend.model.patient;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity model for the `vital_signs` table.
 * Every column in the schema is represented as a field below.
 */
public class VitalSign {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    private String vitalId;
    /** FK -> appointments */
    private String appointmentId;
    private Integer bloodPressureSystolic;
    private Integer bloodPressureDiastolic;
    private Integer heartRate;
    private BigDecimal temperatureCelsius;
    private BigDecimal weightKg;
    private BigDecimal heightCm;
    /** acts as this table's created_at */
    private LocalDateTime recordedAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

    public VitalSign() {
    }

    public VitalSign(String vitalId, String appointmentId, Integer bloodPressureSystolic, Integer bloodPressureDiastolic, Integer heartRate, BigDecimal temperatureCelsius, BigDecimal weightKg, BigDecimal heightCm, LocalDateTime recordedAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        this.vitalId = vitalId;
        this.appointmentId = appointmentId;
        this.bloodPressureSystolic = bloodPressureSystolic;
        this.bloodPressureDiastolic = bloodPressureDiastolic;
        this.heartRate = heartRate;
        this.temperatureCelsius = temperatureCelsius;
        this.weightKg = weightKg;
        this.heightCm = heightCm;
        this.recordedAt = recordedAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public String getVitalId() {
        return vitalId;
    }

    public void setVitalId(String vitalId) {
        this.vitalId = vitalId;
    }

    public String getAppointmentId() {
        return appointmentId;
    }

    public void setAppointmentId(String appointmentId) {
        this.appointmentId = appointmentId;
    }

    public Integer getBloodPressureSystolic() {
        return bloodPressureSystolic;
    }

    public void setBloodPressureSystolic(Integer bloodPressureSystolic) {
        this.bloodPressureSystolic = bloodPressureSystolic;
    }

    public Integer getBloodPressureDiastolic() {
        return bloodPressureDiastolic;
    }

    public void setBloodPressureDiastolic(Integer bloodPressureDiastolic) {
        this.bloodPressureDiastolic = bloodPressureDiastolic;
    }

    public Integer getHeartRate() {
        return heartRate;
    }

    public void setHeartRate(Integer heartRate) {
        this.heartRate = heartRate;
    }

    public BigDecimal getTemperatureCelsius() {
        return temperatureCelsius;
    }

    public void setTemperatureCelsius(BigDecimal temperatureCelsius) {
        this.temperatureCelsius = temperatureCelsius;
    }

    public BigDecimal getWeightKg() {
        return weightKg;
    }

    public void setWeightKg(BigDecimal weightKg) {
        this.weightKg = weightKg;
    }

    public BigDecimal getHeightCm() {
        return heightCm;
    }

    public void setHeightCm(BigDecimal heightCm) {
        this.heightCm = heightCm;
    }

    public LocalDateTime getRecordedAt() {
        return recordedAt;
    }

    public void setRecordedAt(LocalDateTime recordedAt) {
        this.recordedAt = recordedAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return "VitalSign{" + "vitalId=" + vitalId + ", " + "appointmentId=" + appointmentId + ", " + "bloodPressureSystolic=" + bloodPressureSystolic + ", " + "bloodPressureDiastolic=" + bloodPressureDiastolic + ", " + "heartRate=" + heartRate + ", " + "temperatureCelsius=" + temperatureCelsius + ", " + "weightKg=" + weightKg + ", " + "heightCm=" + heightCm + ", " + "recordedAt=" + recordedAt + ", " + "updatedAt=" + updatedAt + ", " + "deletedAt=" + deletedAt + "}";
    }
}